// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDISmyahQprPfqT9_kk46Ertw09U2CgCZw',
    appId: '1:626563395498:web:102a111dc9522d09b7c5d3',
    messagingSenderId: '626563395498',
    projectId: 'toyota-avatar-design',
    authDomain: 'toyota-avatar-design.firebaseapp.com',
    storageBucket: 'toyota-avatar-design.firebasestorage.app',
    measurementId: 'G-NRCEYSR81N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIhH_xlZqt8lQaeKI8_J-wAN1uKzE1m18',
    appId: '1:626563395498:android:d2405b80ad1d72f3b7c5d3',
    messagingSenderId: '626563395498',
    projectId: 'toyota-avatar-design',
    storageBucket: 'toyota-avatar-design.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLa2E_OD1ccGdSm617LcYMIcZl3geIajU',
    appId: '1:626563395498:ios:9d072a14718a22e0b7c5d3',
    messagingSenderId: '626563395498',
    projectId: 'toyota-avatar-design',
    storageBucket: 'toyota-avatar-design.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLa2E_OD1ccGdSm617LcYMIcZl3geIajU',
    appId: '1:626563395498:ios:9d072a14718a22e0b7c5d3',
    messagingSenderId: '626563395498',
    projectId: 'toyota-avatar-design',
    storageBucket: 'toyota-avatar-design.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDISmyahQprPfqT9_kk46Ertw09U2CgCZw',
    appId: '1:626563395498:web:0e85d016cdc01fb7b7c5d3',
    messagingSenderId: '626563395498',
    projectId: 'toyota-avatar-design',
    authDomain: 'toyota-avatar-design.firebaseapp.com',
    storageBucket: 'toyota-avatar-design.firebasestorage.app',
    measurementId: 'G-WYJGZ1F940',
  );

}